version: '{build}'
os: Visual Studio 2015
configuration: Release

before_build:
- ps: (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/4/6/1/46116DFF-29F9-4FF8-94BF-F9BE05BE263B/packages/DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe','core.exe')
- ps: core.exe /install /quiet /norestart
- ps: dotnet restore

build:
  verbosity: minimal

build_script:
- ps: '& ".\build\runner.ps1" Package'

test_script: 
- ps: '& ".\build\runner.ps1" Test'

artifacts:
- path: src\**\bin\**\*.nupkg

deploy:
- provider: Environment
  name: Public Nuget
  on:
    branch: master