version: '{build}'
configuration: Release
before_build:
- ps: '& ".\build\runner.ps1" Package'
build:
#  publish_nuget: true
#  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: artifacts\*.nupkg
deploy:
- provider: Environment
  name: Public Nuget
  on:
    branch: master